import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

// import { Rubik } from "next/font/google";
// const rubik = Rubik({ subsets: ["latin"] });

const mazzard = localFont({
  src: '../public/MazzardSoftH-Regular.otf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mazzard.className}>
      <body>{children}</body>
    </html>
  );
}
